title: Keith Stack # your name (or website title) here
logo: "/images/keith pic.JPG" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data-driven Creator <br><br>
  Data Processing | Data Visualization | Excel | SQL | Tableau  <br><br>
  <a href="https://www.linkedin.com/in/keithstack/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics:  # your Google Analytics tracking ID here
